# Generated by Django 2.1.2 on 2018-11-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0002_auto_20181030_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
