# Generated by Django 2.1.2 on 2018-12-01 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0003_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcarddata',
            name='cvv',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcarddata',
            name='exp_date',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='creditcarddata',
            name='number',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='employerbee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_bee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobfilter',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='jobfilter',
            name='range',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='workerbee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_bee', to=settings.AUTH_USER_MODEL),
        ),
    ]
