# Generated by Django 2.1.2 on 2018-12-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0004_auto_20181201_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='bees.Job'),
        ),
    ]
