# Generated by Django 2.1.2 on 2018-12-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0005_auto_20181201_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobfilter',
            old_name='range',
            new_name='radius',
        ),
    ]
