# Generated by Django 2.1.2 on 2018-12-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0006_auto_20181202_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerbee',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
