# Generated by Django 2.1.2 on 2018-12-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0007_workerbee_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bees.EmployerBee'),
        ),
    ]
