# Generated by Django 2.1.2 on 2018-12-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0009_offer_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerbee',
            name='credit_card',
        ),
        migrations.AddField(
            model_name='employerbee',
            name='braintree_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
