# Generated by Django 2.1.2 on 2018-12-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0010_auto_20181227_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='transaction_id',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
